name: Build & Deploy

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          token: ${{ secrets.DEPLOYTOKEN }}
            
      - name: Pull & update content submodule recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit updates for content submodule
        run: |
          git config user.email "webmotte@marmotteproductions.ch"
          git config user.name "Webmotte"
          git add --all
          git commit -m "chore: Updated content" || echo "No changes to commit"
          git push
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
